# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3
environment: default

image:
  repository: adjust
  tag: latest
  pullPolicy: Never

application:
  deployment: true
  ports:
    - port: 80
      protocol: TCP
  env: []
  probes:
    livenessProbe:
      path: /healthcheck
      port: http
      period: 15
      delay: 10
    readinessProbe:
      path: /healthcheck
      port: http
      period: 15
      delay: 10

volumeMounts: {}

volumes: {}

configMaps: []

autoscaling:
   enabled: false
   minReplicas: 2
   maxReplicas: 4
   targetCPUUtilizationPercentage: 80 # Pods will scale up at this mark

service:
   annotations: {}
#   type: ClusterIP
   ports: 
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}

ingress: []
#  regex: false
#  uris:
#    - path: /
#      type: Prefix

resources:
  requests:
    cpu: 0.01
    memory: 10Mi
  limits:
    cpu: 0.2
    memory: 64Mi

persistence:
  enabled: false

nodeSelector: []
tolerations: []
affinity: {}
podSecurityContext: {}

statefulset:
  podManagementPolicy: "OrderedReady"

cronJobs: []
