{{- range .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    app.kubernetes.io/name: {{ $.Release.Name | quote }}
    app.kubernetes.io/part-of: {{ $.Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ $.Release.Service | quote }}
  namespace: {{ $.Release.Namespace | quote }}
data:
{{ toYaml .data | indent 4 }}
{{- end }}